### ISSUE TITLE
Getting issue when start 'nvim'

### ISSUE THREAD

**Issue by tomzaku** [ChristianChiarulli/nvim#114]
```
[coc.nvim] Error on execute python script: request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
error caught in request handler 'python_execute_file ['/tmp/nvimHEakwY/coc.nvim-26778/coc-ultisnips-ZXsC5clIl3.py', 2, 2]':
Traceback (most recent call last):
  File "/home/xxxxxx/.local/lib/python3.5/site-packages/pynvim/plugin/script_host.py", line 108, in python_execute_file
    script = compile(f.read(), file_path, 'exec')
  File "/tmp/nvimHEakwY/coc.nvim-26778/coc-ultisnips-ZXsC5clIl3.py", line 315
    output += f", ${placeholder_index}"
                                      ^
SyntaxError: invalid syntax
```
```
[coc.nvim] Error on execute python script: request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
error caught in request handler 'python_execute_file ['/tmp/nvim51hsaP/coc.nvim-27026/coc-ultisnips-RiILHq7g1Z.py', 10, 10]':
Traceback (most recent call last):
  File "/home/xxxxxx/.local/lib/python3.5/site-packages/pynvim/plugin/script_host.py", line 108, in python_execute_file
    script = compile(f.read(), file_path, 'exec')
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 19143: ordinal not in range(128)
```
Thank you for this awesome project, I'm using ubuntu and facing this error
Any ideas?

**Comment by tomzaku** [comment]
Is there anything wrong with python 3.5
