### ISSUE TITLE
Ranger crashed

### ISSUE THREAD

**Issue by mikohan** [ChristianChiarulli/nvim#26]
Hi Chris! Thank you for your awesome config! I love it.
I just update config recently and ranger crashes for some reason. Can you help me.
When I trying to run it in nvim I get that error
Thank you for you help!
```
Invalid linemode: devicons; should be metatitle/permissions/fileinfo/filename
ranger version: 1.7.1, executed with python 2.7.12
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 122, in main
    ranger.api.hook_init(fm)
  File "/home/manhee/.config/nvim/autoload/plugged/rnvimr/ranger/plugins/hacks.py", line 377, in <lambda>
    ranger.api.hook_init = lambda fm: Hacks(fm, OLD_HOOK_INIT).hook_init()
  File "/home/manhee/.config/nvim/autoload/plugged/rnvimr/ranger/plugins/hacks.py", line 42, in hook_init
    self.fix_pager()
  File "/home/manhee/.config/nvim/autoload/plugged/rnvimr/ranger/plugins/hacks.py", line 151, in fix_pager
    if not self.commands.get_command('EditFile'):
  File "/usr/lib/python2.7/dist-packages/ranger/api/commands.py", line 62, in get_command
    raise KeyError
KeyError

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

[Process exited 1]
```

**Comment by ChristianChiarulli** [comment]
I think it's because you have the python 2.7 version I would try out the python3 version.

**Comment by kamalkech** [comment]
Python 3.8.5
when open nvim i get this error
```
Error detected while processing function xtabline#render#tabline[18
]..<SNR>166_render_buffers[31]..<lambda>27:
```
